workflows:
  react-native:
    name: React Native Firebase Distribution
    max_build_duration: 60
    environment:
      groups:
        - firebase_credentials
      vars:
        NODE_VERSION: "18"
        GOOGLE_APPLICATION_CREDENTIALS: $FIREBASE_SERVICE_ACCOUNT
      node: "$NODE_VERSION"
      xcode: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd example
          yarn install --frozen-lockfile
      - name: Build Android APK
        script: |
          cd example
          yarn android
      - name: Build iOS app
        script: |
          cd example
          yarn ios
    artifacts:
      - example/android/app/build/outputs/**/*.apk
      - example/ios/build/**/*.ipa
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: $FIREBASE_ANDROID_APP_ID
          artifact_type: 'apk'
          groups: 
            - tester
      email:
        recipients:
          - amr.saied@amwal-pay.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
        submit_to_app_store: false
  package-publish:
    name: Build and Publish Package
    max_build_duration: 30
    environment:
      vars:
        NODE_VERSION: "18"
      node: "$NODE_VERSION"
      java: 17
      groups:
        - npm_credentials
    scripts:
      - name: Install dependencies
        script: |
          yarn install --frozen-lockfile
      - name: Build package
        script: |
          yarn prepare
      - name: Bump version
        script: |
          npm version patch --no-git-tag-version
      - name: Set up npm authentication
        script: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - name: Publish to npm
        script: |
          npm publish --access public